version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            docker build -t dockerapp:v1.0 .
            docker run dockerapp:v1.0 dotnet build
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/addressbookdocker:$CIRCLE_SHA1
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/addressbookdocker:latest
            docker push $DOCKER_HUB_USER_ID/addressbookdocker:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/addressbookdocker:latest